### ISSUE TITLE
Add options for interface name and A vs AAAA

### ISSUE THREAD

**Issue by iiroj** [gstuartj/cf-ddns.sh#2]
Hello,

it would be nice to be able to specify which interface name to get IP addresses from, and whether you want IPv4 or IPv6 (or both). For example:
- `-i=eno1`
- `-t=A` or `-t=AAAA`

I whipped up this script as a wrapper because `cf-ddns.sh` was getting an IPv6 address from the wrong interface (LAN) tried to update it to an A record:

```
#!/bin/sh

ip=`ip addr show eno1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1`
email=""
api_key=""
zone=""
record=""

sh /usr/local/cf-ddns.sh/cf-ddns.sh    \
  -w=$ip                               \
  -e=$email                            \
  -a=$api_key                          \
  -z=$zone                             \
  -r=$record
```

**Comment by gstuartj** [comment]
Just noticed this issue, thanks for submitting. Adding better ipv6 support via AAAA records is an excellent suggestion and will be next on my list. The wrapper script you wrote may be the best way to handle specifying an interface right now, but maybe something better can be done later. Right now I guess it relies on your default route for determining the public IP.
